### ISSUE TITLE
CI errors on linting

### ISSUE THREAD

**Issue by kerzhner** [statechannels/go-nitro-testground#71]
https://github.com/statechannels/go-nitro-testground/runs/8186378977?check_suite_focus=true

Potentially related to https://github.com/golangci/golangci-lint/issues/3107

**Comment by lalexgap** [comment]
I believe this is due to CI using `go 1.19` (since we use a version range) and the version of `golangci-lint` we're using on ci (`v1.45.2`) not properly supporting go 1.19.

I think this can be resolved by upgrading to a later version of `golangci-lint` like we did in [go-nitro](https://github.com/statechannels/go-nitro/pull/821)
